# Generated by Django 3.2.4 on 2021-07-01 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=30)),
                ('ultimoNome', models.CharField(max_length=30)),
                ('idade', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('commentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('answer5', models.CharField(max_length=100)),
                ('answer6', models.CharField(max_length=100)),
                ('answer7', models.CharField(max_length=100)),
                ('answer8', models.CharField(max_length=100)),
                ('answer9', models.CharField(max_length=100)),
                ('answer10', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
